Server:
  Port: 8902
  ReadTimeout: 15s
  WriteTimeout: 15s

API:
  BasePath: ""
  APITimeout: 15s
  EnableSwagger: true

Database:
  SlaveDSN: "postgres://postgres:1235813@localhost:5433/vote?sslmode=disable"
  MasterDSN: "postgres://postgres:1235813@localhost:5433/vote?sslmode=disable"
  RetryInterval: 10
  MaxIdleConn: 10
  MaxConn: 10
  ConnMaxLifetime: 10s

Kafka:
  Producer:
    Brokers:
      - localhost:9092
    MaxAttempt: 5
    Idempotent: true
  Topics:
    VoteSubmitData:
      Value: "votes.submit"
      ErrorHandler: "Phase1"
      WithBackOff: true


JWT:
  Secret: "^87adb2&91hnGaWd7"

GrpcServer:
  Port: 35000

Encryption:
  Key : "NZkrqmVGg6Bi4QbqGXbH9wz3Q0+NCGvMKA2j8hqD5eM="

BlockchainConfig:
  GanacheURL: "http://127.0.0.1:7545"
  VotechainAddress: "0x9942546a784daFADD13549b2937156307577D38c"
  ElectionManagerAddress: "0xD3c14E5de1Fa4Dd1A3662B2F6fCf6c9b6bce248F"
  KPUManagerAddress: "0xac10688B8C5ed19007CC6c1296E8155C3630db94"
  VoterManagerAddress: "0xac10688B8C5ed19007CC6c1296E8155C3630db94"
  VotechainBaseAddress: "0xBcDc1f66f7C4adEE4980567a29ba3687a7FCB294"


Cors:
  AllowOrigins: "*"
  AllowMethods: "GET,POST,PUT,DELETE,OPTIONS"
  AllowHeaders: "Content-Type,Authorization, X-User-Id, X-Role, X-Address, Ngrok-Skip-Browser-Warning"
  AllowCredentials: false
  ExposeHeaders: "X-Custom-Header"
  MaxAge: 3600g