// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_repository

import (
	context "context"

	model "github.com/nocturna-ta/vote/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ElectionTimeRepository is an autogenerated mock type for the ElectionTimeRepository type
type ElectionTimeRepository struct {
	mock.Mock
}

// ActivateElectionTime provides a mock function with given fields: ctx, id
func (_m *ElectionTimeRepository) ActivateElectionTime(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ActivateElectionTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateElectionTime provides a mock function with given fields: ctx, electionTime
func (_m *ElectionTimeRepository) CreateElectionTime(ctx context.Context, electionTime *model.ElectionTime) error {
	ret := _m.Called(ctx, electionTime)

	if len(ret) == 0 {
		panic("no return value specified for CreateElectionTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ElectionTime) error); ok {
		r0 = rf(ctx, electionTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeactivateAllElections provides a mock function with given fields: ctx
func (_m *ElectionTimeRepository) DeactivateAllElections(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateAllElections")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteElectionTime provides a mock function with given fields: ctx, id
func (_m *ElectionTimeRepository) DeleteElectionTime(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteElectionTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveElectionTime provides a mock function with given fields: ctx
func (_m *ElectionTimeRepository) GetActiveElectionTime(ctx context.Context) (*model.ElectionTime, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveElectionTime")
	}

	var r0 *model.ElectionTime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.ElectionTime, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.ElectionTime); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ElectionTime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllElectionTimes provides a mock function with given fields: ctx, limit, offset
func (_m *ElectionTimeRepository) GetAllElectionTimes(ctx context.Context, limit int, offset int) ([]model.ElectionTime, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllElectionTimes")
	}

	var r0 []model.ElectionTime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]model.ElectionTime, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []model.ElectionTime); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ElectionTime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCurrentElectionTime provides a mock function with given fields: ctx
func (_m *ElectionTimeRepository) GetCurrentElectionTime(ctx context.Context) (*model.ElectionTime, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentElectionTime")
	}

	var r0 *model.ElectionTime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.ElectionTime, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.ElectionTime); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ElectionTime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetElectionTimeByID provides a mock function with given fields: ctx, id
func (_m *ElectionTimeRepository) GetElectionTimeByID(ctx context.Context, id uuid.UUID) (*model.ElectionTime, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetElectionTimeByID")
	}

	var r0 *model.ElectionTime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.ElectionTime, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.ElectionTime); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ElectionTime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetElectionsToActivate provides a mock function with given fields: ctx
func (_m *ElectionTimeRepository) GetElectionsToActivate(ctx context.Context) ([]*model.ElectionTime, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetElectionsToActivate")
	}

	var r0 []*model.ElectionTime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.ElectionTime, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.ElectionTime); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ElectionTime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExpiredActiveElections provides a mock function with given fields: ctx
func (_m *ElectionTimeRepository) GetExpiredActiveElections(ctx context.Context) ([]*model.ElectionTime, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiredActiveElections")
	}

	var r0 []*model.ElectionTime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.ElectionTime, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.ElectionTime); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ElectionTime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateElectionTime provides a mock function with given fields: ctx, electionTime
func (_m *ElectionTimeRepository) UpdateElectionTime(ctx context.Context, electionTime *model.ElectionTime) error {
	ret := _m.Called(ctx, electionTime)

	if len(ret) == 0 {
		panic("no return value specified for UpdateElectionTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ElectionTime) error); ok {
		r0 = rf(ctx, electionTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateElectionTimeStatus provides a mock function with given fields: ctx, id, status, isActive
func (_m *ElectionTimeRepository) UpdateElectionTimeStatus(ctx context.Context, id uuid.UUID, status model.ElectionStatus, isActive bool) error {
	ret := _m.Called(ctx, id, status, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateElectionTimeStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.ElectionStatus, bool) error); ok {
		r0 = rf(ctx, id, status, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewElectionTimeRepository creates a new instance of ElectionTimeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewElectionTimeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ElectionTimeRepository {
	mock := &ElectionTimeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
