// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_repository

import (
	context "context"

	model "github.com/nocturna-ta/vote/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VoteRepository is an autogenerated mock type for the VoteRepository type
type VoteRepository struct {
	mock.Mock
}

// GetFailedVotes provides a mock function with given fields: ctx, limit, offset
func (_m *VoteRepository) GetFailedVotes(ctx context.Context, limit int, offset int) ([]*model.Vote, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetFailedVotes")
	}

	var r0 []*model.Vote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*model.Vote, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*model.Vote); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Vote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingVotes provides a mock function with given fields: ctx, limit, offset
func (_m *VoteRepository) GetPendingVotes(ctx context.Context, limit int, offset int) ([]*model.Vote, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingVotes")
	}

	var r0 []*model.Vote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*model.Vote, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*model.Vote); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Vote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoteByElectionPairID provides a mock function with given fields: ctx, electionPairID
func (_m *VoteRepository) GetVoteByElectionPairID(ctx context.Context, electionPairID uuid.UUID) (*model.Vote, error) {
	ret := _m.Called(ctx, electionPairID)

	if len(ret) == 0 {
		panic("no return value specified for GetVoteByElectionPairID")
	}

	var r0 *model.Vote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Vote, error)); ok {
		return rf(ctx, electionPairID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Vote); ok {
		r0 = rf(ctx, electionPairID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Vote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, electionPairID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoteByID provides a mock function with given fields: ctx, id
func (_m *VoteRepository) GetVoteByID(ctx context.Context, id uuid.UUID) (*model.Vote, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVoteByID")
	}

	var r0 *model.Vote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Vote, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Vote); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Vote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertVote provides a mock function with given fields: ctx, vote
func (_m *VoteRepository) InsertVote(ctx context.Context, vote *model.Vote) error {
	ret := _m.Called(ctx, vote)

	if len(ret) == 0 {
		panic("no return value specified for InsertVote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Vote) error); ok {
		r0 = rf(ctx, vote)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertVoteBlockchain provides a mock function with given fields: ctx, signedTransaction
func (_m *VoteRepository) InsertVoteBlockchain(ctx context.Context, signedTransaction string) (string, error) {
	ret := _m.Called(ctx, signedTransaction)

	if len(ret) == 0 {
		panic("no return value specified for InsertVoteBlockchain")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, signedTransaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, signedTransaction)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, signedTransaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateVote provides a mock function with given fields: ctx, vote
func (_m *VoteRepository) UpdateVote(ctx context.Context, vote *model.Vote) error {
	ret := _m.Called(ctx, vote)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Vote) error); ok {
		r0 = rf(ctx, vote)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateVoteStatus provides a mock function with given fields: ctx, id, status
func (_m *VoteRepository) UpdateVoteStatus(ctx context.Context, id uuid.UUID, status model.VoteStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVoteStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.VoteStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVoteRepository creates a new instance of VoteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VoteRepository {
	mock := &VoteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
