// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"

	event "github.com/nocturna-ta/golib/event"
	mock "github.com/stretchr/testify/mock"
)

// Consumer is an autogenerated mock type for the Consumer type
type Consumer struct {
	mock.Mock
}

// ConsumeVoteSubmit provides a mock function with given fields: ctx, message
func (_m *Consumer) ConsumeVoteSubmit(ctx context.Context, message *event.EventConsumeMessage) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeVoteSubmit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *event.EventConsumeMessage) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsumer creates a new instance of Consumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Consumer {
	mock := &Consumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
