// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"

	request "github.com/nocturna-ta/vote/internal/usecases/request"
	mock "github.com/stretchr/testify/mock"

	response "github.com/nocturna-ta/vote/internal/usecases/response"

	uuid "github.com/google/uuid"
)

// ElectionTimeUseCases is an autogenerated mock type for the ElectionTimeUseCases type
type ElectionTimeUseCases struct {
	mock.Mock
}

// ActivateElection provides a mock function with given fields: ctx, id
func (_m *ElectionTimeUseCases) ActivateElection(ctx context.Context, id uuid.UUID) (*response.ElectionTimeResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ActivateElection")
	}

	var r0 *response.ElectionTimeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*response.ElectionTimeResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *response.ElectionTimeResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ElectionTimeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateElectionTime provides a mock function with given fields: ctx, req
func (_m *ElectionTimeUseCases) CreateElectionTime(ctx context.Context, req *request.CreateElectionTimeRequest) (*response.ElectionTimeResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateElectionTime")
	}

	var r0 *response.ElectionTimeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.CreateElectionTimeRequest) (*response.ElectionTimeResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.CreateElectionTimeRequest) *response.ElectionTimeResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ElectionTimeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.CreateElectionTimeRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteElectionTime provides a mock function with given fields: ctx, id
func (_m *ElectionTimeUseCases) DeleteElectionTime(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteElectionTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCurrentElectionStatus provides a mock function with given fields: ctx
func (_m *ElectionTimeUseCases) GetCurrentElectionStatus(ctx context.Context) (*response.ElectionStatusResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentElectionStatus")
	}

	var r0 *response.ElectionStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*response.ElectionStatusResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *response.ElectionStatusResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ElectionStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetElectionTimeByID provides a mock function with given fields: ctx, id
func (_m *ElectionTimeUseCases) GetElectionTimeByID(ctx context.Context, id uuid.UUID) (*response.ElectionTimeResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetElectionTimeByID")
	}

	var r0 *response.ElectionTimeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*response.ElectionTimeResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *response.ElectionTimeResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ElectionTimeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SyncElectionStatuses provides a mock function with given fields: ctx
func (_m *ElectionTimeUseCases) SyncElectionStatuses(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SyncElectionStatuses")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateElectionTime provides a mock function with given fields: ctx, id, req
func (_m *ElectionTimeUseCases) UpdateElectionTime(ctx context.Context, id uuid.UUID, req *request.UpdateElectionTimeRequest) (*response.ElectionTimeResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateElectionTime")
	}

	var r0 *response.ElectionTimeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *request.UpdateElectionTimeRequest) (*response.ElectionTimeResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *request.UpdateElectionTimeRequest) *response.ElectionTimeResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ElectionTimeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *request.UpdateElectionTimeRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewElectionTimeUseCases creates a new instance of ElectionTimeUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewElectionTimeUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *ElectionTimeUseCases {
	mock := &ElectionTimeUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
