// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"

	request "github.com/nocturna-ta/vote/internal/usecases/request"
	mock "github.com/stretchr/testify/mock"

	response "github.com/nocturna-ta/vote/internal/usecases/response"
)

// OTPUseCases is an autogenerated mock type for the OTPUseCases type
type OTPUseCases struct {
	mock.Mock
}

// GenerateOTP provides a mock function with given fields: ctx, req
func (_m *OTPUseCases) GenerateOTP(ctx context.Context, req *request.GenerateOTPRequest) (*response.GenerateOTPResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GenerateOTP")
	}

	var r0 *response.GenerateOTPResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.GenerateOTPRequest) (*response.GenerateOTPResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.GenerateOTPRequest) *response.GenerateOTPResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.GenerateOTPResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.GenerateOTPRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOTPStatus provides a mock function with given fields: ctx, voterID, purpose
func (_m *OTPUseCases) GetOTPStatus(ctx context.Context, voterID string, purpose string) (*response.OTPStatusResponse, error) {
	ret := _m.Called(ctx, voterID, purpose)

	if len(ret) == 0 {
		panic("no return value specified for GetOTPStatus")
	}

	var r0 *response.OTPStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*response.OTPStatusResponse, error)); ok {
		return rf(ctx, voterID, purpose)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *response.OTPStatusResponse); ok {
		r0 = rf(ctx, voterID, purpose)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.OTPStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, voterID, purpose)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResendOTP provides a mock function with given fields: ctx, req
func (_m *OTPUseCases) ResendOTP(ctx context.Context, req *request.ResendOTPRequest) (*response.ResendOTPResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ResendOTP")
	}

	var r0 *response.ResendOTPResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ResendOTPRequest) (*response.ResendOTPResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.ResendOTPRequest) *response.ResendOTPResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ResendOTPResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.ResendOTPRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateOTPToken provides a mock function with given fields: ctx, voterID, purpose, token
func (_m *OTPUseCases) ValidateOTPToken(ctx context.Context, voterID string, purpose string, token string) (bool, error) {
	ret := _m.Called(ctx, voterID, purpose, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateOTPToken")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return rf(ctx, voterID, purpose, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = rf(ctx, voterID, purpose, token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, voterID, purpose, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyOTP provides a mock function with given fields: ctx, req
func (_m *OTPUseCases) VerifyOTP(ctx context.Context, req *request.VerifyOTPRequest) (*response.VerifyOTPResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOTP")
	}

	var r0 *response.VerifyOTPResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.VerifyOTPRequest) (*response.VerifyOTPResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.VerifyOTPRequest) *response.VerifyOTPResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.VerifyOTPResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.VerifyOTPRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOTPUseCases creates a new instance of OTPUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOTPUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *OTPUseCases {
	mock := &OTPUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
