// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"

	request "github.com/nocturna-ta/vote/internal/usecases/request"
	mock "github.com/stretchr/testify/mock"

	response "github.com/nocturna-ta/vote/internal/usecases/response"

	uuid "github.com/google/uuid"
)

// VoteUseCases is an autogenerated mock type for the VoteUseCases type
type VoteUseCases struct {
	mock.Mock
}

// CastVote provides a mock function with given fields: ctx, req
func (_m *VoteUseCases) CastVote(ctx context.Context, req *request.CastVoteRequest) (*response.CastVoterResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CastVote")
	}

	var r0 *response.CastVoterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.CastVoteRequest) (*response.CastVoterResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.CastVoteRequest) *response.CastVoterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.CastVoterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.CastVoteRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoteStatus provides a mock function with given fields: ctx, voteID
func (_m *VoteUseCases) GetVoteStatus(ctx context.Context, voteID uuid.UUID) (*response.VoteStatusResponse, error) {
	ret := _m.Called(ctx, voteID)

	if len(ret) == 0 {
		panic("no return value specified for GetVoteStatus")
	}

	var r0 *response.VoteStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*response.VoteStatusResponse, error)); ok {
		return rf(ctx, voteID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *response.VoteStatusResponse); ok {
		r0 = rf(ctx, voteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.VoteStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, voteID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVoteUseCases creates a new instance of VoteUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoteUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *VoteUseCases {
	mock := &VoteUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
