// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_infrastructures

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SMSProvider is an autogenerated mock type for the SMSProvider type
type SMSProvider struct {
	mock.Mock
}

// GetProviderName provides a mock function with no fields
func (_m *SMSProvider) GetProviderName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProviderName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SendSMS provides a mock function with given fields: ctx, to, message
func (_m *SMSProvider) SendSMS(ctx context.Context, to string, message string) error {
	ret := _m.Called(ctx, to, message)

	if len(ret) == 0 {
		panic("no return value specified for SendSMS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, to, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidatePhoneNumber provides a mock function with given fields: phoneNumber
func (_m *SMSProvider) ValidatePhoneNumber(phoneNumber string) error {
	ret := _m.Called(phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePhoneNumber")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(phoneNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSMSProvider creates a new instance of SMSProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSMSProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *SMSProvider {
	mock := &SMSProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
