basePath: /
definitions:
  controller.errorResponse:
    properties:
      error_code:
        type: integer
      error_message:
        type: string
    type: object
  controller.jsonResponse:
    properties:
      code:
        type: integer
      data: {}
      error:
        $ref: '#/definitions/controller.errorResponse'
      message:
        type: string
    type: object
  request.CastVoteRequest:
    properties:
      election_pair_id:
        type: string
      otp_token:
        type: string
      region:
        type: string
      signed_transaction:
        type: string
      voter_id:
        type: string
    type: object
  request.CreateElectionTimeRequest:
    properties:
      description:
        type: string
      end_time:
        type: string
      start_time:
        type: string
      title:
        type: string
    type: object
  request.GenerateOTPRequest:
    properties:
      phone_number:
        type: string
      purpose:
        type: string
      voter_id:
        type: string
    required:
    - phone_number
    - purpose
    - voter_id
    type: object
  request.ResendOTPRequest:
    properties:
      phone_number:
        type: string
      purpose:
        type: string
      voter_id:
        type: string
    required:
    - phone_number
    - purpose
    - voter_id
    type: object
  request.UpdateElectionTimeRequest:
    properties:
      description:
        type: string
      end_time:
        type: string
      start_time:
        type: string
      title:
        type: string
    type: object
  request.VerifyOTPRequest:
    properties:
      code:
        type: string
      purpose:
        type: string
      voter_id:
        type: string
    required:
    - code
    - purpose
    - voter_id
    type: object
  response.CastVoterResponse:
    properties:
      id:
        type: string
      status:
        type: string
      tx_hash:
        type: string
      voted_at:
        type: string
    type: object
  response.ElectionStatusResponse:
    properties:
      current_election:
        $ref: '#/definitions/response.ElectionTimeResponse'
      is_election_active:
        type: boolean
      message:
        type: string
      remaining_voting_time:
        type: string
      time_until_end:
        type: integer
      time_until_start:
        type: integer
    type: object
  response.ElectionTimeResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      end_time:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      start_time:
        type: string
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  response.GenerateOTPResponse:
    properties:
      expires_at:
        type: string
      max_attempts:
        type: integer
      message:
        type: string
      purpose:
        type: string
      remaining_attempts:
        type: integer
      time_remaining_seconds:
        type: string
      voter_id:
        type: string
    type: object
  response.OTPStatusResponse:
    properties:
      attempt_count:
        type: integer
      can_resend:
        type: boolean
      expires_at:
        type: string
      max_attempts:
        type: integer
      purpose:
        type: string
      remaining_attempts:
        type: integer
      status:
        type: string
      time_remaining_seconds:
        type: string
      voter_id:
        type: string
    type: object
  response.ResendOTPResponse:
    properties:
      expires_at:
        type: string
      max_attempts:
        type: integer
      message:
        type: string
      purpose:
        type: string
      remaining_attempts:
        type: integer
      time_remaining_seconds:
        type: string
      voter_id:
        type: string
    type: object
  response.VerifyOTPResponse:
    properties:
      is_valid:
        type: boolean
      message:
        type: string
      otp_token:
        type: string
      purpose:
        type: string
      token_expiry:
        type: string
      verified_at:
        type: string
      voter_id:
        type: string
    type: object
  response.VoteStatusResponse:
    properties:
      error_message:
        type: string
      id:
        type: string
      processed_at:
        type: string
      status:
        type: string
      tx_hash:
        type: string
      voted_at:
        type: string
    type: object
info:
  contact: {}
  description: Voting Service.
  title: Voting Service
  version: 1.0.0
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Ping to check health
      parameters:
      - description: user that make request
        in: header
        name: X-User-Id
        type: string
      - default: web
        description: channel where request comes from
        in: header
        name: X-Channel-Id
        type: string
      - description: request unique identifier
        in: header
        name: X-Request-Id
        type: string
      - description: user account
        in: header
        name: X-Account-Id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.jsonResponse'
      summary: Ping
      tags:
      - Health
  /v1/election-time:
    post:
      consumes:
      - application/json
      description: Create a new election time
      parameters:
      - description: Authorized User
        in: header
        name: X-User-Id
        type: string
      - description: Authorized Address
        in: header
        name: X-Address
        type: string
      - description: Authorized Role
        in: header
        name: X-Role
        type: string
      - description: Create Election Time Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateElectionTimeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ElectionTimeResponse'
              type: object
      summary: Create Election Time
      tags:
      - ElectionTime
  /v1/election-time/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an existing election time
      parameters:
      - description: Authorized User
        in: header
        name: X-User-Id
        type: string
      - description: Authorized Address
        in: header
        name: X-Address
        type: string
      - description: Authorized Role
        in: header
        name: X-Role
        type: string
      - description: Election Time ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.jsonResponse'
      summary: Delete Election Time
      tags:
      - ElectionTime
    get:
      consumes:
      - application/json
      description: Get an election time by its ID
      parameters:
      - description: Authorized User
        in: header
        name: X-User-Id
        type: string
      - description: Authorized Address
        in: header
        name: X-Address
        type: string
      - description: Authorized Role
        in: header
        name: X-Role
        type: string
      - description: Election Time ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ElectionTimeResponse'
              type: object
      summary: Get Election Time by ID
      tags:
      - ElectionTime
    put:
      consumes:
      - application/json
      description: Update an existing election time
      parameters:
      - description: Authorized User
        in: header
        name: X-User-Id
        type: string
      - description: Authorized Address
        in: header
        name: X-Address
        type: string
      - description: Authorized Role
        in: header
        name: X-Role
        type: string
      - description: Election Time ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Election Time Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UpdateElectionTimeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ElectionTimeResponse'
              type: object
      summary: Update Election Time
      tags:
      - ElectionTime
  /v1/election-time/{id}/activate:
    post:
      consumes:
      - application/json
      description: Manually activate an election time
      parameters:
      - description: Authorized User
        in: header
        name: X-User-Id
        type: string
      - description: Authorized Address
        in: header
        name: X-Address
        type: string
      - description: Authorized Role
        in: header
        name: X-Role
        type: string
      - description: Election Time ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ElectionTimeResponse'
              type: object
      summary: Manually Activate Election
      tags:
      - ElectionTime
  /v1/election-time/status:
    get:
      consumes:
      - application/json
      description: Get the current election status
      parameters:
      - description: Authorized User
        in: header
        name: X-User-Id
        type: string
      - description: Authorized Address
        in: header
        name: X-Address
        type: string
      - description: Authorized Role
        in: header
        name: X-Role
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ElectionStatusResponse'
              type: object
      summary: Get Current Election Status
      tags:
      - ElectionTime
  /v1/election-time/sync:
    post:
      consumes:
      - application/json
      description: Sync the statuses of all election times
      parameters:
      - description: Authorized User
        in: header
        name: X-User-Id
        type: string
      - description: Authorized Address
        in: header
        name: X-Address
        type: string
      - description: Authorized Role
        in: header
        name: X-Role
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.jsonResponse'
      summary: Sync Election Statuses
      tags:
      - ElectionTime
  /v1/otp/generate:
    post:
      consumes:
      - application/json
      description: Generate a new OTP for the specified voter and purpose
      parameters:
      - description: Generate OTP request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.GenerateOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.GenerateOTPResponse'
              type: object
      summary: Generate OTP
      tags:
      - OTP
  /v1/otp/resend:
    post:
      consumes:
      - application/json
      description: Resend OTP for the specified voter and purpose
      parameters:
      - description: Resend OTP request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.ResendOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ResendOTPResponse'
              type: object
      summary: Resend OTP
      tags:
      - OTP
  /v1/otp/status:
    get:
      consumes:
      - application/json
      description: Get the current status of OTP for a voter and purpose
      parameters:
      - description: Voter ID
        in: query
        name: voter_id
        required: true
        type: string
      - description: OTP Purpose
        in: query
        name: purpose
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.OTPStatusResponse'
              type: object
      summary: Get OTP Status
      tags:
      - OTP
  /v1/otp/verify:
    post:
      consumes:
      - application/json
      description: Verify the provided OTP code
      parameters:
      - description: Verify OTP request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.VerifyOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.VerifyOTPResponse'
              type: object
      summary: Verify OTP
      tags:
      - OTP
  /v1/vote/{id}/status:
    get:
      consumes:
      - application/json
      description: Get vote status
      parameters:
      - description: Authorized User
        in: header
        name: X-User-Id
        type: string
      - description: Authorized Address
        in: header
        name: X-Address-Id
        type: string
      - description: Authorized Role
        in: header
        name: X-Role
        type: string
      - description: Vote ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.VoteStatusResponse'
              type: object
      summary: Get vote status
      tags:
      - Vote
  /v1/vote/cast:
    post:
      consumes:
      - application/json
      description: Cast a vote
      parameters:
      - description: Cast vote request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CastVoteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.CastVoterResponse'
              type: object
      summary: Cast a vote
      tags:
      - Vote
swagger: "2.0"
